name: Need Tests Label

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

permissions:
  pull-requests: write

jobs:
  check-need-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check for core code changes without tests
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner: context.repo.owner, repo: context.repo.repo, pull_number: pr.number }
            );
            const coreChanged = files.some(f => f.filename.startsWith('django/'));
            const testsChanged = files.some(f => f.filename.startsWith('tests/'));
            const label = "need tests";
            const labels = pr.labels.map(l => l.name);

            if (coreChanged && !testsChanged && !labels.includes(label)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [label]
              });
              console.log(`Added "${label}" label to PR #${pr.number}`);
            }
            else if ((!coreChanged || testsChanged) && labels.includes(label)) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                name: label
              });
              console.log(`Removed "${label}" label from PR #${pr.number}`);
            } else {
              console.log("No label change needed.");
            }