name: Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read  # For commenting on PRs

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - '3.13'
    name: Windows, SQLite, Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for diff-cover
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'tests/requirements/py3.txt'
      - name: Install and upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install test dependencies
        run: python -m pip install -r tests/requirements/py3.txt -e .
      - name: Run tests with coverage
        run: python -Wall tests/runtests.py -v2
        env:
          COVERAGE_PROCESS_START: ${{ github.workspace }}/tests/.coveragerc
      - name: Generate coverage report
        run: |
          coverage combine
          coverage report --show-missing
      - name: Run diff-cover for PRs
        if: github.event_name == 'pull_request'
        run: |
          pip install diff-cover
          diff-cover .coverage --compare-branch=origin/main --fail-under=0 --output-file=diff-cover-report.md
        continue-on-error: true
      - name: Comment coverage report on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const fs = require('fs');
              const reportPath = 'diff-cover-report.md';
              
              if (fs.existsSync(reportPath)) {
                const report = fs.readFileSync(reportPath, 'utf8');
                
                const comment = `## 📊 Coverage Report for Changed Files
            
            ${report}
            
            **Note:** Missing lines are shown as warnings only. Some lines may not be covered by SQLite tests as they are database-specific.`;
                
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              } else {
                console.log('No diff-cover report found');
              }
            } catch (error) {
              console.error('Error creating comment:', error);
            }

  javascript-tests:
    runs-on: ubuntu-latest
    name: JavaScript tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      - run: npm install
      - run: npm test
